name: lint

on:
  push:
    branches:
    - development
    - staging
    - main
  pull_request:
jobs: # list of things to do
  linting:
    name: Linting
    runs-on: ubuntu-latest # on which machine to run
    steps: # list of steps
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn

      - name: Code Linting
        run: yarn run lint

      # - name: Code format checking
      #   run: npm run format:check